dateModified: 1616079770
email:
  fromEmail: support@craftcms.com
  fromName: 'Craft test site'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  magic-login:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft test site'
  schemaVersion: 5.0.0.20
  timeZone: Europe/London
users:
  allowPublicRegistration: true
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: false
