name: Create Release

on: 
  workflow_dispatch:
    branches: 
      - 1.x
      - 2.x
      - 3.x
      - 4.x

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction

    - name: Setup Commit User
      run: |
        git config --local user.email "creode-dev@users.noreply.github.com"
        git config --local user.name "Creode Developer"

    - name: Push Release
      run: |
        composer run-script release
        git push --tags origin HEAD